server:
  port: 8080
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/StivenYang/SpringCloud-Project
          username:
          password:
          search-paths: config-repo