server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/StivenYang/SpringBoot-Project
          search-paths: /parent/springcloud-config/respo
          username:
          password:
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/
